'use strict';

const DEFAULT_GROUP    = 'test';
const EXPLICIT_LISTING = '%%EXPLICIT_LISTING%%';
const MEMBER_LISTING   = '%%GROUP_MEMBERS_LISTING%%';

module.exports = { DEFAULT_GROUP, EXPLICIT_LISTING, MEMBER_LISTING };

